select2boxes.settings:
  type: config_object
  label: 'Select2Boxes Settings'
  mapping:
    provider:
      type: string
      label: 'Provider type'
    version:
      type: string
      label: 'Library version'
    url:
      type: string
      label: 'CDN URL'
    limited_search:
      type: boolean
      label: 'Limit search box visibility by list length'
    minimum_search_length:
      type: integer
      label: 'Minimum list length'
    select2_global:
      type: boolean
      label: 'Enable select2 widgets for all dropdown and multiselect lists'
    disable_for_admin_pages:
      type: boolean
      label: 'Disable select2 widgets for admin pages'

field.widget.third_party.select2boxes:
  type: mapping
  label: 'Third party settings of Select2Boxes'
  mapping:
    enable_preload:
      type: boolean
      label: 'Enable preload'
    preload_count:
      type: integer
      label: 'Preload count'
    enable_flags:
      type: boolean
      label: 'Include flags icons'
    enable_select2:
      type: boolean
      label: 'Enable Select2 widget for dropdowns'
